# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Python dependencies (pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]

  # API server (Node.js) dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "api"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Known compatibility issues
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]

  # Web dashboard (React/Vite) dependencies
  - package-ecosystem: "npm"
    directory: "/web-content"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nodejs"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/dockerfile"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "your-team/devops-reviewers"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  # Group all pytest plugins together
  python-testing:
    patterns:
      - "pytest*"
    update-types:
      - "minor"
      - "patch"

  # Group all linting tools together
  python-linting:
    patterns:
      - "black"
      - "ruff"
      - "mypy"
    update-types:
      - "minor"
      - "patch"

  # Group React ecosystem updates
  react-ecosystem:
    patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    update-types:
      - "minor"
      - "patch"

  # Group build tools
  build-tools:
    patterns:
      - "vite"
      - "typescript"
      - "tsconfig"
    update-types:
      - "minor"
      - "patch"
