[tool.docker-compose]
validate = "python .config/validate_stacks.py"
build = "python .config/validate_stacks.py --build"
test = "python .config/validate_stacks.py --build --test"
clean = "python .config/validate_stacks.py --cleanup && docker system prune -f"
up = "docker-compose -f .config/basic-stack/docker-compose.yml up -d"
down = "docker-compose -f .config/basic-stack/docker-compose.yml down"
logs = "docker-compose -f .config/basic-stack/docker-compose.yml logs -f"
ps = "docker-compose -f .config/basic-stack/docker-compose.yml ps"

[tool.docker-compose.help]
description = "Docker Compose Management - Available commands: validate, build, test, clean, up, down, logs, ps"

[tool.docker-compose.config]
config_folder = ".config"

# Minimal TOML referencing .config for all paths and scripts
# Makefile removed; all commands are now managed via pyproject.toml
