# BuildKit Daemon Configuration
# Enterprise-grade configuration with 250GB cache, multi-platform support, and advanced GC
# Aligned with Docker Desktop v0.25.1 beta features and daemon.json settings
#
# BuildKit Features:
# - 250GB build cache (aligned with daemon.json)
# - Multi-platform: amd64, arm64, riscv64, ppc64le, s390x, arm/v7, arm/v6
# - 50 max parallelism (aligned with concurrent downloads/uploads)
# - 7-day build history retention
# - Advanced garbage collection policies

# Debug logging
debug = false

# Root directory for buildkit state
root = "/var/lib/buildkit"

# Worker configuration
[worker.oci]
  enabled = true
  # Multi-platform support (aligned with Docker Desktop v0.25.1)
  platforms = ["linux/amd64", "linux/arm64", "linux/riscv64", "linux/ppc64le", "linux/s390x", "linux/arm/v7", "linux/arm/v6"]
  max-parallelism = 50  # Aligned with max-concurrent-downloads/uploads
  gc = true
  gckeepstorage = 268435456000  # 250GB (aligned with daemon.json)

  # GC policy configuration
  [[worker.oci.gcpolicy]]
    keepBytes = 214748364800  # 200GB
    keepDuration = 259200     # 3 days in seconds
    filters = ["type==source.local,type==exec.cachemount,type==source.git.checkout"]

  [[worker.oci.gcpolicy]]
    all = true
    keepBytes = 53687091200  # 50GB
    keepDuration = 172800     # 2 days in seconds

[worker.containerd]
  enabled = false

# Registry configuration for mirrors and authentication
[registry."docker.io"]
  mirrors = ["mirror.gcr.io"]

[registry."registry-1.docker.io"]
  http = false

# gRPC server configuration
[grpc]
  address = ["tcp://0.0.0.0:1234"]

  [grpc.tls]
    cert = ""
    key = ""
    ca = ""

# Build history configuration
[history]
  maxAge = 604800     # 7 days in seconds (longer retention with larger cache)
  maxEntries = 500    # Increased for 250GB cache environment
