services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_runner:latest
    container_name: docker_runner
    environment:
      - GITHUB_URL=${GITHUB_URL:-https://github.com/user/docker}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - RUNNER_NAME=${RUNNER_NAME:-docker-runner}
      - RUNNER_WORKDIR=${RUNNER_WORKDIR:-/actions-runner/_work}
      - LABELS=${LABELS:-self-hosted,linux,x64}
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
    volumes:
      - docker_runner_data:/actions-runner
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

volumes:
  docker_runner_data:
