---
# Basic Stack Configuration - CI/CD Automation
# Generated: 2025-10-24
# Description: Config-driven automation for basic development stack

# Stack Metadata
stack:
  name: "basic-stack"
  description: "Development and testing environment with all core services"
  version: "3.0"
  purpose: "Local development, CI/CD pipelines, basic testing"
  type: "development"

# CI/CD Configuration
ci_cd:
  github_actions:
    workflow: "basic-stack.yml"
    triggers:
      - push:
          branches: [main, develop]
      - pull_request:
          branches: [main]
    environment: "development"

  docker:
    build_context: "../../.dockerfiles"
    build_args:
      ENVIRONMENT: "development"
      SERVICE_TYPE: "basic"
      WORKERS: "1"
    image_tag: "docker_examples_basic:latest"
    registry: "docker.io"

  testing:
    framework: "pytest"
    coverage_target: "80"
    security_scan: true
    performance_test: false

# Environment Variables (Config-Driven)
environment:
  # Application Configuration
  ENVIRONMENT: "development"
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"

  # Security Configuration
  API_KEY: "${API_KEY}"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  CORS_ORIGINS: "http://localhost:3000"
  SECURITY_HEADERS_ENABLED: "true"
  INPUT_VALIDATION_ENABLED: "true"

  # Database Configuration
  POSTGRES_DB: "mydb"
  POSTGRES_USER: "user"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

  # Redis Configuration
  REDIS_URL: "redis://redis:6379"
  REDIS_DB: "0"

  # External APIs
  GITHUB_TOKEN: "${GITHUB_TOKEN}"

# Service Configuration (References to docker-compose.yml)
services:
  python:
    port: 8000
    health_endpoint: "/health"
    api_docs: "/docs"
  node:
    port: 3000
    dev_server: true
  db:
    port: 5432
    database: "mydb"
  redis:
    port: 6379

# Volume Configuration (Named volumes for persistence)
volumes:
  db_data: "docker_examples_db_data"
  db_logs: "docker_examples_db_logs"
  redis_data: "docker_examples_redis_data"
  python_app: "docker_examples_python_app"
  node_app: "docker_examples_node_app"
  python_mcp: "docker_examples_python_mcp"  # MCP utilities volume

# Secrets Configuration (Environment Variable Driven)
secrets:
  db_password:
    env_var: "DOCKER_EXAMPLES_DB_PASSWORD"
    source: "../../.secrets/secrets.env"
    description: "PostgreSQL database password loaded from environment variables"

# Network Configuration
network:
  name: "docker_examples_basic_stack_network"
  driver: "bridge"

# Health Checks Configuration
health_checks:
  overall_timeout: "300s"
  service_startup_order: ["db", "redis", "python", "node"]
  required_services: ["db", "redis", "python", "node"]

# Resource Limits (Config-Driven)
resource_limits:
  python:
    cpus: "1.0"
    memory: "1g"
  node:
    cpus: "0.5"
    memory: "512m"
  db:
    cpus: "0.5"
    memory: "512m"
  redis:
    cpus: "0.25"
    memory: "256m"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  log_level: "DEBUG"

# Development Configuration
development:
  hot_reload: true
  debug_mode: true
  auto_restart: true
  volume_mounts:
    - source: "../../.dockerfiles"
      target: "/dockerfiles"
      type: "bind"

# Deployment Configuration
deployment:
  compose_file: "../../.compose/basic-stack/docker-compose.yml"
  scale_defaults:
    python: 1
    node: 1
    db: 1
    redis: 1
  restart_policy: "unless-stopped"