global:
  resolve_timeout: 5m
  # SMTP configuration for email notifications
  smtp_smarthost: 'cluster-mailhog:1025'
  smtp_from: 'alertmanager@docker-cluster.local'
  smtp_require_tls: false

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 5m
    
    # Warning alerts - grouped notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 1h

# Receivers configuration
receivers:
  - name: 'default'
    email_configs:
      - to: 'team@docker-cluster.local'
        headers:
          Subject: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.cluster }}'
        html: |
          <h2>Alert: {{ .GroupLabels.alertname }}</h2>
          <p><strong>Cluster:</strong> {{ .GroupLabels.cluster }}</p>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p><small>Firing alerts: {{ .Alerts.Firing | len }}</small></p>

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@docker-cluster.local'
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        html: |
          <h1 style="color: red;">🚨 CRITICAL ALERT</h1>
          <h2>{{ .GroupLabels.alertname }}</h2>
          <p><strong>Cluster:</strong> {{ .GroupLabels.cluster }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <hr>
          <p>⚠️ Immediate action required!</p>
    
    # Webhook for Slack/Teams integration (example)
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@docker-cluster.local'
        headers:
          Subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        html: |
          <h2 style="color: orange;">⚠️ WARNING ALERT</h2>
          <h3>{{ .GroupLabels.alertname }}</h3>
          <p><strong>Cluster:</strong> {{ .GroupLabels.cluster }}</p>
          <p><strong>Service:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Inhibit warning if critical is firing for same alert
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  
  # Inhibit container alerts if host is down
  - source_match:
      alertname: 'HostDown'
    target_match_re:
      alertname: 'Container.*'
    equal: ['instance']

