global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'docker-cluster'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker containers via cAdvisor (if added)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']

  # PostgreSQL exporter (if added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis exporter (if added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Nginx exporters
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets:
  #       - 'cluster-loadbalancer:9113'
  #       - 'cluster-web1:9113'
  #       - 'cluster-web2:9113'
  #       - 'cluster-web3:9113'

  # Node exporter (if added)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
