# BuildKit Daemon Configuration
# Optimized for local development with aggressive caching

[worker.oci]
  enabled = true
  platforms = ["linux/amd64", "linux/arm64"]
  max-parallelism = 4

[worker.containerd]
  enabled = false

# Garbage collection settings
[worker.oci.gc]
  enabled = true
  keepBytes = 10737418240  # 10GB
  keepDuration = 259200     # 3 days in seconds
  
[worker.oci.gcpolicy]
  [[worker.oci.gcpolicy.all]]
    keepBytes = 5368709120  # 5GB
    keepDuration = 172800    # 2 days
    
  [[worker.oci.gcpolicy.all]]
    keepBytes = 2147483648  # 2GB
    keepDuration = 86400     # 1 day

# Registry mirror and cache settings
[registry."docker.io"]
  mirrors = ["mirror.gcr.io"]
  
[registry."registry.hub.docker.com"]
  insecure = false
  ca = []
  
# Build cache settings
[worker.oci.snapshotter]
  name = "overlayfs"

# Debug and tracing
[grpc]
  address = ["tcp://0.0.0.0:1234"]
  uid = 1000
  gid = 1000

# History and export settings
[history]
  maxAge = 259200  # 3 days
  maxEntries = 100
