services:
  python:
    build:
      context: ../../../..
      dockerfile: .docker-compose/mcp/python_utils/dockerfiles/python.Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ./.docker-compose/mcp/python_utils:/app:cached
      - react_scuba_python_venv:/app/.venv
      - react_scuba_python_cache:/root/.cache/pip
      - react_scuba_python_pytest_cache:/tmp/.cache/pytest
      - react_scuba_python_mypy_cache:/tmp/.cache/mypy
      - react_scuba_python_ruff_cache:/tmp/.cache/ruff
    working_dir: /app
    command: sh -c "pip install -e python_utils && python -m react_scuba_utils.api"
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/python_utils:/app
      - PYTHONOPTIMIZE=1
      - PYTHONDONTWRITEBYTECODE=1
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - mcp-python-network
    healthcheck:
      test:
        ["CMD", "python", "-c", "import sys; print('Python OK'); sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test-runner:
    build:
      context: ../../../..
      dockerfile: .docker-compose/mcp/python_utils/dockerfiles/python.Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ./.docker-compose/mcp/python_utils:/app:cached
      - react_scuba_python_venv:/app/.venv
      - react_scuba_python_cache:/root/.cache/pip
      - react_scuba_python_pytest_cache:/tmp/.cache/pytest
      - react_scuba_python_mypy_cache:/tmp/.cache/mypy
      - react_scuba_python_ruff_cache:/tmp/.cache/ruff
      - react_scuba_test_coverage:/app/htmlcov
    working_dir: /app
    command: sh -c "pip install -e python_utils && python -m pytest tests/ -v --cov=react_scuba_utils --cov-report=html --cov-report=term"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/python_utils:/app
      - PYTHONOPTIMIZE=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - mcp-python-network
    profiles:
      - test
    depends_on:
      python:
        condition: service_healthy

volumes:
  react_scuba_python_venv:
    driver: local
  react_scuba_python_cache:
    driver: local
  react_scuba_python_pytest_cache:
    driver: local
  react_scuba_python_mypy_cache:
    driver: local
  react_scuba_python_ruff_cache:
    driver: local
  react_scuba_test_coverage:
    driver: local

networks:
  mcp-python-network:
    driver: bridge
