# Promtail Configuration for Docker Compose
# Collects logs from Docker containers and sends to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Set container name as job label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Set container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      # Set compose project
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
      # Set compose service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      # Set image name
      - source_labels: ['__meta_docker_container_label_com_docker_compose_image']
        target_label: 'image'
    # Pipeline stages for log processing
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            msg: message
            timestamp: timestamp
      - labels:
          level:
          
  # System logs (optional)
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
