# ============================================================================
# Base Configuration - Core MkDocs Settings
# ============================================================================

# Validation Rules
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: ignore

# Extra Files to Include
extra:
  # Version Management
  version:
    provider: mike
    default: latest

  # Social Links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DeanLuus22021994/docker_dotfiles
      name: GitHub Repository
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/deanluus22021994
      name: Docker Hub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deanluus
      name: LinkedIn Profile
    - icon: fontawesome/solid/envelope
      link: mailto:dean.luus@example.com
      name: Email Contact

  # Status Badges
  status:
    production: Production Ready
    beta: Beta Testing
    experimental: Experimental
    deprecated: Deprecated

  # Feature Toggles
  features:
    analytics: true
    comments: false
    feedback: true

  # Announcement Bar (dynamic)
  announcement:
    enabled: !ENV [ANNOUNCEMENT_ENABLED, false]
    message: !ENV [ANNOUNCEMENT_MESSAGE, ""]

# Analytics (Google Analytics 4)
extra_analytics:
  provider: google
  property: !ENV [GA_MEASUREMENT_ID, "G-XXXXXXXXXX"]

# Consent Management (GDPR Compliant)
extra_consent:
  title: Cookie Consent
  description: |
    We use cookies to recognize your repeated visits, measure effectiveness,
    and understand how you interact with our documentation.
  cookies:
    analytics:
      name: Google Analytics
      checked: false
  actions:
    - accept
    - reject
    - manage
