services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - node_modules:/workspaces/node_modules
      - python_venv:/workspaces/.venv
    working_dir: /workspaces
    command: sleep infinity
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      db:
        condition: service_healthy
      node:
        condition: service_healthy
      python:
        condition: service_healthy
    networks:
      - basic-stack-network
    profiles:
      - dev

  node:
    build:
      context: ../..
      dockerfile: .docker-compose/basic-stack/dockerfiles/node.Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ../..:/app:cached
      - docker_examples_node_modules:/app/node_modules
      - docker_examples_node_cache:/root/.npm
      - docker_examples_node_yarn_cache:/usr/local/share/.cache/yarn
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm start"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - basic-stack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  python:
    build:
      context: ../..
      dockerfile: .docker-compose/mcp/python_utils/dockerfiles/python.Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - ../mcp/python_utils:/app:cached
      - docker_examples_python_venv:/app/.venv
      - docker_examples_python_cache:/root/.cache/pip
      - docker_examples_python_pytest_cache:/tmp/.cache/pytest
      - docker_examples_python_mypy_cache:/tmp/.cache/mypy
      - docker_examples_python_ruff_cache:/tmp/.cache/ruff
    working_dir: /app
    command: sh -c "pip install -e . && python -m docker_examples_utils.api"
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app
      - BASIC_MODE=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - basic-stack-network
    healthcheck:
      test:
        ["CMD", "python", "-c", "import sys; print('Python OK'); sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    build:
      context: ../..
      dockerfile: .docker-compose/basic-stack/dockerfiles/postgres.Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    secrets:
      - db_password
    volumes:
      - docker_examples_db_data:/var/lib/postgresql/data
      - docker_examples_db_logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - basic-stack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  docker_examples_db_data:
    driver: local
  docker_examples_db_logs:
    driver: local
  docker_examples_node_modules:
    driver: local
  docker_examples_node_cache:
    driver: local
  docker_examples_node_yarn_cache:
    driver: local
  docker_examples_python_venv:
    driver: local
  docker_examples_python_cache:
    driver: local
  docker_examples_python_pytest_cache:
    driver: local
  docker_examples_python_mypy_cache:
    driver: local
  docker_examples_python_ruff_cache:
    driver: local

networks:
  basic-stack-network:
    driver: bridge

secrets:
  db_password:
    file: ../../secrets/db_password.txt
