---
# Docker Compose - Cluster Example
# Generated: 2025-10-24
# Description: Load-balanced multi-instance deployment configuration

services:
  python:
    image: "docker_examples_python:latest"
    build:
      context: "../.docker-compose/cluster-example/dockerfiles"
      dockerfile: "python.Dockerfile"
    ports:
      - "8001:8000"
      - "8002:8000"
      - "8003:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - SERVICE_NAME=python
    volumes:
      - docker_examples_python_app:/app
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

  node:
    image: "docker_examples_node:latest"
    build:
      context: "../.docker-compose/cluster-example/dockerfiles"
      dockerfile: "node.Dockerfile"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - docker_examples_node_app:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - docker_examples_nginx_config:/etc/nginx
    depends_on:
      - python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: "postgres:15"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    volumes:
      - docker_examples_db_data:/var/lib/postgresql/data
      - docker_examples_db_logs:/var/log/postgresql
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - docker_examples_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  docker_examples_db_data:
    driver: local
  docker_examples_db_logs:
    driver: local
  docker_examples_redis_data:
    driver: local
  docker_examples_python_app:
    driver: local
  docker_examples_node_app:
    driver: local
  docker_examples_nginx_config:
    driver: local

secrets:
  db_password:
    file: ../../secrets/db_password.txt

networks:
  default:
    name: docker_examples_cluster_example_network
    driver: bridge