name: Agent Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  agent-deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push agent image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .dockerfiles/agent.Dockerfile
          push: true
          tags: docker/copilot-agent:latest,docker/copilot-agent:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to staging
        run: |
          echo "Deploying GitHub Copilot agent to staging environment..."
          # Add your deployment logic here
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
          AGENT_CONFIG: ${{ secrets.AGENT_CONFIG }}