name: Agent Integration Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  agent-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --extra agent --extra agent-dev

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Test agent initialization
        run: |
          uv run python -c "
          import asyncio
          from agent_app import GitHubCopilotAgent, CopilotAgentConfig

          async def test():
              config = CopilotAgentConfig()
              agent = GitHubCopilotAgent(config)
              await agent.initialize()
              result = await agent.run_task('Test task')
              print(f'Agent test result: {result}')
              await agent.shutdown()

          asyncio.run(test())
          print('Agent integration test passed')
          "

      - name: Test agent tools
        run: |
          uv run python -c "
          import asyncio
          from agent_app import GitHubCopilotAgent, CopilotAgentConfig

          async def test_tools():
              config = CopilotAgentConfig()
              agent = GitHubCopilotAgent(config)
              await agent.initialize()
              tools = list(agent.tools.keys())
              print(f'Available tools: {tools}')
              assert len(tools) > 0, 'No tools available'
              await agent.shutdown()

          asyncio.run(test_tools())
          print('Agent tools test passed')
          "