name: GitHub Copilot Agent CI/CD

on:
  workflow_dispatch:
    inputs:
      run_validation:
        description: 'Run agent validation'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      run_integration:
        description: 'Run integration tests'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      run_deployment:
        description: 'Run deployment'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Agent Validation
        if: github.event.inputs.run_validation == 'true' || github.event_name != 'workflow_dispatch'
        run: |
          echo "Triggering agent validation workflow..."
          gh workflow run agent-validation.yml

      - name: Run Agent Integration Test
        if: github.event.inputs.run_integration == 'true'
        run: |
          echo "Triggering agent integration test workflow..."
          gh workflow run agent-integration-test.yml

      - name: Run Agent Deployment
        if: github.event.inputs.run_deployment == 'true'
        run: |
          echo "Triggering agent deployment workflow..."
          gh workflow run agent-deployment.yml